name: CI
on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  build:
    name: cargo +${{ matrix.rust }} build
    strategy:
      matrix:
        rust:
          - 1.33.0
          - 1.35.0
          - 1.36.0
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - run: rustup target add thumbv7m-none-eabi
      - run: cargo build
      - run: cargo build --target thumbv7m-none-eabi
