name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

jobs:
  build:
    strategy:
      matrix:
        rust:
          - 1.33.0
          - 1.35.0
          - 1.36.0
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: ${{ matrix.rust }}
      - run: rustup target add thumbv7m-none-eabi
      - run: cargo build
      - run: cargo build --target thumbv7m-none-eabi
